### ISSUE TITLE
Installation issue, file not found

### ISSUE THREAD

**Issue by NicolleLouis** [MathIsFun0/Immolate#32]
Hello, thanks for the hard work. I'm on Linux. 

When following the ReadMe and installing the project, I ran into this file not found error: 

`
./build/Immolate
`

`
Immolate Beta v1.0.1f.1
Warning: Kernel not found at /home/louis/Project/Immolate/build/search.cl, attempting working directory...
Building program...
In file included from stringInput.cl:1:
./filters/erratic_flush_five.cl:2:10: fatal error: 'lib/immolate.cl' file not found

Fatal CL Error -45 when trying to execute clCreateKernel - Creating OpenCL kernel
`

**Comment by MathIsFun0** [comment]
It appears that for some reason it wasn't able to find the immolate.cl file. Is it located in `./lib/immolate.cl`?

If so, then you may need to run Immolate in the main directory (i.e. the path of the Immolate binary should be `/home/louis/Project/Immolate/Immolate`)

**Comment by NicolleLouis** [comment]
Actually I seemed to have an issue with my OpenCl installation (Intel). I reinstalled it and now the issue seems gone.

I have those logs instead:

`(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
(null) ()
Fatal CL Error -5 when trying to execute clEnqueueNDRangeKernel - Executing OpenCL kernel`

Those maybe regular, let me look more at the Troubleshooting :)
